In [1]:
import pandas as pd
#import matplotlib.pyplot as plt
#import datetime

In [2]:
# Use pd.read_csv() (or the appropriate Pandas reader) to bring your file into a DataFrame.
csv_file = pd.read_csv("../Data/Crime_Data_2016.csv")
df = csv_file

In [3]:
df.head()

,INCIDENT_NUMBER,DATE_REPORTED,DATE_OCCURED,UOR_DESC,CRIME_TYPE,NIBRS_CODE,UCR_HIERARCHY,ATT_COMP,LMPD_DIVISION,LMPD_BEAT,PREMISE_TYPE,BLOCK_ADDRESS,CITY,ZIP_CODE,ID,ObjectId
0,80-16-080765,9/20/16 12:42 PM,9/14/16 7:30 AM,HARASSMENT (NO PHYSICAL CONTACT),ASSAULT,13C,PART II,COMPLETED,5TH DIVISION,525,RESIDENCE / HOME,3900 BLOCK LELAND RD ...,BELLEWOOD,40207.0,34,1
1,80-16-064276,7/29/16 2:38 PM,7/28/16 11:30 PM,RECEIVING STOLEN PROPERTY (FIREARM),THEFT/LARCENY,280,PART II,COMPLETED,7TH DIVISION,723,RESIDENCE / HOME,8400 BLOCK SILVER FOX RD ...,LOUISVILLE,40291.0,325,2
2,80-16-000805,3/7/16 9:59 AM,2/28/04 12:00 AM,COLD CASE REPORT NUMBER,OTHER,999,NaN,COMPLETED,4TH DIVISION,412,OTHER / UNKNOWN,700 BLOCK S SHELBY ST ...,LOUISVILLE,40203.0,521,3
3,80-16-099509,11/21/16 9:53 AM,1/18/04 8:00 PM,COLD CASE REPORT NUMBER,OTHER,999,NaN,COMPLETED,2ND DIVISION,225,OTHER / UNKNOWN,1400 BLOCK STANDARD VILLAGE CIR ...,LOUISVILLE,40210.0,522,4
4,80-16-099506,11/21/16 9:53 AM,7/19/04 7:00 PM,COLD CASE REPORT NUMBER,OTHER,999,NaN,COMPLETED,4TH DIVISION,436,OTHER / UNKNOWN,100 BLOCK E WOODLAWN AVE ...,LOUISVILLE,40214.0,960,5

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84535 entries, 0 to 84534
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   INCIDENT_NUMBER  84535 non-null  object
 1   DATE_REPORTED    84535 non-null  object
 2   DATE_OCCURED     84531 non-null  object
 3   UOR_DESC         84535 non-null  object
 4   CRIME_TYPE       84535 non-null  object
 5   NIBRS_CODE       84535 non-null  object
 6   UCR_HIERARCHY    82719 non-null  object
 7   ATT_COMP         84276 non-null  object
 8   LMPD_DIVISION    84535 non-null  object
 9   LMPD_BEAT        84483 non-null  object
 10  PREMISE_TYPE     84422 non-null  object
 11  BLOCK_ADDRESS    84535 non-null  object
 12  CITY             84352 non-null  object
 13  ZIP_CODE         83683 non-null  float64
 14  ID               84535 non-null  int64
 15  ObjectId         84535 non-null  int64
dtypes: float64(1), int64(2), object(13)
memory usage: 10.3+ MB

In [5]:
df.rename(columns={"ObjectId": "OBJECTID"}, inplace=True)

In [6]:
df.shape

(84535, 16)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.value_counts()

INCIDENT_NUMBER  DATE_REPORTED     DATE_OCCURED       UOR_DESC                                           CRIME_TYPE                NIBRS_CODE  UCR_HIERARCHY  ATT_COMP   LMPD_DIVISION  LMPD_BEAT  PREMISE_TYPE                       BLOCK_ADDRESS                                                 CITY        ZIP_CODE  ID       OBJECTID
80-00-999999     2/1/16 11:39 AM   2/1/16 12:00 AM    POSS OF MARIJUANA                                  DRUGS/ALCOHOL VIOLATIONS  35A         PART II        COMPLETED  8TH DIVISION   812        HIGHWAY / ROAD / ALLEY             3100 BLOCK N HURSTBOURNE PKY                                  LOUISVILLE  40241.0   1182910  24318       1
80-15-106622     1/1/16 12:18 AM   12/31/15 11:54 PM  TBUT OR DISP AUTO > $10,000 BUT < $1,000,000       MOTOR VEHICLE THEFT       240         PART I         COMPLETED  1ST DIVISION   123        PARKING LOT / GARAGE               100 BLOCK S 11TH ST                                           LOUISVILLE  40203.0   1148001  1511        1
80-15-106628     1/1/16 1:16 AM    6/1/15 11:59 PM    THEFT OF MOTOR VEHICLE REGISTRATION PLATE/DECAL    VEHICLE BREAK-IN/THEFT    23G         PART I         COMPLETED  6TH DIVISION   612        SERVICE / GAS STATION              4900 BLOCK POPLAR LEVEL RD                                    LOUISVILLE  40219.0   1147840  710         1
80-15-106631     1/1/16 2:04 AM    12/17/15 12:00 AM  TBUT OR DISP FROM BLDG $500 OR > BUT < $10,000     THEFT/LARCENY             23D         PART I         COMPLETED  1ST DIVISION   134        RESIDENCE / HOME                   1300 BLOCK E MAIN ST                                          LOUISVILLE  40206.0   1148369  2594        1
80-15-106636     1/1/16 2:40 AM    12/30/15 8:45 PM   CRIMINAL MISCHIEF - 1ST DEGREE                     VANDALISM                 290         PART II        COMPLETED  7TH DIVISION   724        COMMERCIAL / OFFICE BUILDING       11600 BLOCK ANTONIA WAY                                       LOUISVILLE  40229.0   1147739  523         1
                                                                                                                                                                                                                                                                                                                                              ..
80-17-088710     5/15/16 11:13 AM  5/15/16 11:13 AM   MENACING                                           ASSAULT                   13C         PART II        COMPLETED  6TH DIVISION   613        HIGHWAY / ROAD / ALLEY             BISHOP LN / PINEWOOD RD                                       LOUISVILLE  40218.0   40590    46          1
80-17-099652     9/1/16 10:14 AM   8/31/16 12:01 AM   CRIMINAL ABUSE-1ST DEGREE-CHILD 12 OR UNDER        ASSAULT                   13A         PART I         COMPLETED  1ST DIVISION   123        RESIDENCE / HOME                   1100 BLOCK W MUHAMMAD ALI BLVD                                LOUISVILLE  40203.0   174910   135         1
80-18-054459     5/16/16 1:22 PM   5/16/16 1:22 PM    THEFT BY FAIL TO MAKE REQ DISPOSITION OF PROPERTY  FRAUD                     26A         PART II        COMPLETED  1ST DIVISION   112        RENTAL / STORAGE FACILITY          2100 BLOCK W BROADWAY                                         LOUISVILLE  40211.0   346562   90          1
80-20-034023     7/29/16 10:12 PM  7/29/16 10:00 PM   TBUT OR DISP SHOPLIFTING $500 OR >  BUT < $10,000  THEFT/LARCENY             23C         PART I         COMPLETED  8TH DIVISION   812        DEPARTMENT / DISCOUNT STORE        4200 BLOCK TOWNE CENTER DR                                    LOUISVILLE  40241.0   1120424  341         1
IN-AC-TIVE       12/19/16 8:28 PM  12/19/16 6:00 PM   CRIMINAL MISCHIEF-3RD DEGREE                       VANDALISM                 290         PART II        COMPLETED  7TH DIVISION   736        OTHER RESIDENCE (APARTMENT/CONDO)  9000 BLOCK PEGASUS POINTE DR                                  LOUISVILLE  40219.0   1256963  72348       1
Name: count, Length: 81940, dtype: int64

In [9]:
df.describe()

            ZIP_CODE            ID     OBJECTID
count   83683.000000  8.453500e+04  84535.00000
mean    40229.630785  1.202712e+06  42268.00000
std      3133.489000  6.067738e+04  24403.29684
min         1.000000  3.400000e+01      1.00000
25%     40209.000000  1.178976e+06  21134.50000
50%     40214.000000  1.203722e+06  42268.00000
75%     40220.000000  1.232208e+06  63401.50000
max    944091.000000  1.318581e+06  84535.00000

In [10]:
df.corr(numeric_only=True)

          ZIP_CODE        ID  OBJECTID
ZIP_CODE  1.000000 -0.002465 -0.004570
ID       -0.002465  1.000000  0.558746
OBJECTID -0.004570  0.558746  1.000000

In [11]:
df.nunique()

INCIDENT_NUMBER    70433
DATE_REPORTED      62937
DATE_OCCURED       48099
UOR_DESC             494
CRIME_TYPE            16
NIBRS_CODE            51
UCR_HIERARCHY          2
ATT_COMP               2
LMPD_DIVISION          9
LMPD_BEAT             54
PREMISE_TYPE          48
BLOCK_ADDRESS      16151
CITY                  91
ZIP_CODE              52
ID                 84535
OBJECTID           84535
dtype: int64

In [12]:
df.isnull().sum()

INCIDENT_NUMBER       0
DATE_REPORTED         0
DATE_OCCURED          4
UOR_DESC              0
CRIME_TYPE            0
NIBRS_CODE            0
UCR_HIERARCHY      1816
ATT_COMP            259
LMPD_DIVISION         0
LMPD_BEAT            52
PREMISE_TYPE        113
BLOCK_ADDRESS         0
CITY                183
ZIP_CODE            852
ID                    0
OBJECTID              0
dtype: int64

In [13]:
print(df["UOR_DESC"].value_counts().describe())
print(df["UOR_DESC"].value_counts())

count     494.000000
mean      171.123482
std       537.206423
min         1.000000
25%         2.000000
50%         7.000000
75%        57.000000
max      4308.000000
Name: count, dtype: float64
UOR_DESC
TBUT OR DISP SHOPLIFTING < $500                                 4308
DRUG PARAPHERNALIA - BUY/POSSESS                                4028
BURGLARY - 2ND DEGREE                                           3765
CRIMINAL MISCHIEF-3RD DEGREE                                    3752
TBUT OR DISP CONTENTS FROM VEH < $500                           3500
                                                                ...
RECEIVE GOODS, ETC BY FRAUD U/$500 WITHIN 6 MO MISD                1
TBUT OR DISP FROM SHIPMENT $10,000 OR > BUT  < $1,000,000          1
MANUFACTURE SIMULATED CONTROLLED SUBSTANCE-1ST OFFENSE             1
EAVESDROPPING                                                      1
RECEIVING STOLEN PROPERTY (ANHYDROUS AMMONIA) W/INTENT TO MA       1
Name: count, Length: 494, dtype: int64

In [14]:
print(df["CRIME_TYPE"].value_counts().describe())
print(df["CRIME_TYPE"].value_counts())

count       16.000000
mean      5283.437500
std       5391.623762
min          5.000000
25%        588.500000
50%       4379.500000
75%       7090.250000
max      15720.000000
Name: count, dtype: float64
CRIME_TYPE
THEFT/LARCENY               15720
ASSAULT                     14204
DRUGS/ALCOHOL VIOLATIONS    13802
OTHER                        9080
VEHICLE BREAK-IN/THEFT       6427
VANDALISM                    6256
BURGLARY                     6088
MOTOR VEHICLE THEFT          4410
FRAUD                        4349
ROBBERY                      1579
WEAPONS                      1359
DISTURBING THE PEACE          612
SEX CRIMES                    518
HOMICIDE                      115
ARSON                          11
DUI                             5
Name: count, dtype: int64

In [15]:
print(df["ATT_COMP"].value_counts().describe())
print(df["ATT_COMP"].value_counts())

count        2.000000
mean     42138.000000
std      57673.043287
min       1357.000000
25%      21747.500000
50%      42138.000000
75%      62528.500000
max      82919.000000
Name: count, dtype: float64
ATT_COMP
COMPLETED    82919
ATTEMPTED     1357
Name: count, dtype: int64

In [16]:
print(df["LMPD_DIVISION"].value_counts().describe())
print(df["LMPD_DIVISION"].value_counts())

count        9.000000
mean      9392.777778
std       4247.472418
min       1362.000000
25%       6161.000000
50%      10285.000000
75%      11921.000000
max      14574.000000
Name: count, dtype: float64
LMPD_DIVISION
4TH DIVISION        14574
3RD DIVISION        13832
1ST DIVISION        11921
2ND DIVISION        10801
6TH DIVISION        10285
7TH DIVISION         9872
8TH DIVISION         6161
5TH DIVISION         5727
METRO LOUISVILLE     1362
Name: count, dtype: int64

In [17]:
print(df["ZIP_CODE"].value_counts().describe())
print(df["ZIP_CODE"].value_counts())

count      52.000000
mean     1609.288462
std      1831.433054
min         1.000000
25%         1.750000
50%       914.000000
75%      2608.500000
max      5905.000000
Name: count, dtype: float64
ZIP_CODE
40203.0     5905
40211.0     5851
40214.0     5807
40219.0     5577
40212.0     4339
40215.0     4252
40216.0     4102
40272.0     3998
40210.0     3718
40202.0     3611
40218.0     3431
40208.0     3136
40258.0     2823
40213.0     2537
40204.0     2482
40291.0     2180
40229.0     2158
40206.0     2051
40220.0     1986
40205.0     1668
40241.0     1536
40217.0     1475
40222.0     1353
40228.0     1072
40118.0      962
40299.0      917
40245.0      911
40223.0      833
40243.0      763
40209.0      762
40207.0      723
40242.0      416
40059.0      205
40023.0       47
40177.0       32
40056.0       24
40225.0       23
40165.0        2
40014.0        2
48226.0        1
47112.0        1
944091.0       1
66209.0        1
10215.0        1
4015.0         1
40324.0        1
40408.0        1
40010.0        1
40601.0        1
42141.0        1
40145.0        1
1.0            1
Name: count, dtype: int64